language: java
sudo: true
jdk:
  - openjdk11
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker
before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
after_success:
  - bash <(curl -s https://codecov.io/bash)